package models

type Address struct {
	Id                 int    `json:"id"`
	FiasId             string `json:"fias_id"`
	FiasLevel          string `json:"fias_level"`
	FiasCode           string `json:"fias_code"`
	FiasActualityState string `json:"fias_actuality_state"`
	Full               string `json:"full"`
	UnrestrictedValue  string `json:"unrestricted_value"`
	Country            string `json:"country"`
	CountryId          int    `json:"-"`
	Region             string `json:"region"`
	RegionFiasId       string `json:"region_fias_id"`
	RegionType         string `json:"region_type"`
	RegionWithType     string `json:"region_with_type"`
	City               string `json:"city"`
	CityFiasId         string `json:"city_fias_id"`
	CityType           string `json:"city_type"`
	CityWithType       string `json:"city_with_type"`
	CapitalMarker      string `json:"capital_marker"`
	CityArea           string `json:"city_area"`
	Area               string `json:"area"`
	AreaFiasId         string `json:"area_fias_id"`
	AreaType           string `json:"area_type"`
	AreaWithType       string `json:"area_with_type"`
	Settlement         string `json:"settlement"`
	SettlementFiasId   string `json:"settlement_fias_id"`
	SettlementType     string `json:"settlement_type"`
	SettlementWithType string `json:"settlement_with_type"`
	Street             string `json:"street"`
	StreetFiasId       string `json:"street_fias_id"`
	StreetType         string `json:"street_type"`
	StreetWithType     string `json:"street_with_type"`
	PostalCode         string `json:"postal_code"`
	House              string `json:"house"`
	HouseFiasId        string `json:"house_fias_id"`
	HouseType          string `json:"house_type"`
	Block              string `json:"block"`
	BlockType          string `json:"block_type"`
	Flat               string `json:"flat"`
	FlatType           string `json:"flat_type"`
	TaxOffice          string `json:"tax_office"`
	TaxOfficeLegal     string `json:"tax_office_legal"`
	Okato              string `json:"okato"`
	Oktmo              string `json:"oktmo"`
	GeoLat             string `json:"geo_lat"`
	GeoLon             string `json:"geo_lon"`
	QcGeo              string `json:"qc_geo"`
}
